version: '3'
services:
  todofront:
    image: todofrontend
    restart: on-failure
    container_name: front_1
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    image: todobackend
    restart: on-failure
    container_name: back_1
    ports:
      - 3001:3001
  todotests:
    image: todotests
    container_name: tests_1
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront #Nome do serviço
